### ISSUE TITLE
W3C validation issues from itemprops on tabs, author attributes on post grids, 

### ISSUE THREAD

**Issue by covertnine** [covertnine/c9-blocks#21]
The tabs are throwing errors on W3C's validator for the HTML as well as a few other items I'll detail below.

- Tabs (both sets are giving errors on the tab-butotn names)
- author props on the post grid markup

It's coming from the itemprop names on the tab content themselves and the names the tabs are assigned. You can see it on line 212 below

**/c9-blocks/src/blocks/block-vertical-tabs/edit.js**

`											id={`tab-button-${slug}`}
`

The tab-button naming exists in a few different files, so if you just update the aria-labeledby prop on the tab content it will get rid of the error.

The other errors are all coming from the posts grid block when you show the author name, excerpt, etc.

Should just be a few quick markup edits, and testing to make sure changing the markup doesn't break anything. There aren't any stylings applied to aria labels so it should just be a markup thing.

Create a test page, load in sample blog post info, then copy and paste that markup into the W3C validator and you'll see the specific markup issues related to itemscope.

https://validator.w3.org/nu/#textarea

**Comment by htmercury** [comment]
Fixed the markup w3c issues related to both tab blocks and post grid block mentioned on develop branch. Current blocks may need to be re-saved to see the changes, however any new created blocks will have the adjusted markup.

**Comment by covertnine** [comment]
Excellent. I'll get it all tested.

We'll have to merge all this together here sometime in the next week or two so I can make sure it works with WP 5.5
