### ISSUE TITLE
Vertically align center by default when equal height slides is selected

### ISSUE THREAD

**Issue by covertnine** [covertnine/c9-blocks#24]
Slides currently align to top (even with a c9 column container set to align vertically centered, it aligns to the top with a slide that is taller in another slide.

There should be a CSS solution to take the parent container's class so that inner containers are centered vertically by default. (flexbox would be justify-content: center; align: center;)

Not technically a bug, more like a preference for the alignments of inner slider containers when the outer setting is set to be equal height. (It'll look better design-wise, and if at all possible, this could be toggle-able secondary set of settings in the inspector for center top or bottom alignment when using the "equal height columns" setting.

Open to other suggestions. I can help with the SCSS for this after I get through 3-4 other bugs/enhancements I'm working on.

[screen recording of top alignment](https://recordit.co/0DPgAU9ROO)

**Comment by htmercury** [comment]
Just to leave for reference here, pushes for vertical alignment on slides blocks completed since [commit 627a428585029a6994e91ba59ef48f8074738f5d](https://github.com/covertnine/c9-blocks/commit/627a428585029a6994e91ba59ef48f8074738f5d)
