### ISSUE TITLE
Error notice from WordPress 5.5

### ISSUE THREAD

**Issue by covertnine** [covertnine/c9-blocks#26]
PHP Notice:  register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>c9-blocks/v1/tuts</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.

Some issue with our REST API calls to the tutorials. Anything we need to fix?

**Comment by covertnine** [comment]
To recreate, instal WP 5.5, and latest develop branch (I've made a few layout bug fixes) these were showing up on edit pages briefly and in the debug logs.

**Comment by htmercury** [comment]
I looked into the error message and pushed a recent fix on the develop branch! let me know if that fixes it.

**Comment by covertnine** [comment]
I actually found a fix for this and should have taken it down.

just had to return that API call true. Looks like we found the same thing!

-Tim
