### ISSUE TITLE
Video Backgrounds causing JS error Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by covertnine** [covertnine/c9-blocks#29]
Getting some JS errors from the youtube video backgrounds on this page with Autoptimize enabled:
https://www.covertnine.com/slant/

`blocks.frontend.build.js?ver=5.6:1 Uncaught TypeError: Cannot read property 'parentNode' of undefined
    at o (blocks.frontend.build.js?ver=5.6:1)
    at L.r.J (www-widgetapi.js:340)
    at Ni (www-widgetapi.js:599)
    at Z.r.fa (www-widgetapi.js:623)
    at Qf.l (www-widgetapi.js:411)
    at Bf.g (www-widgetapi.js:396)`

**Comment by dskrepps** [comment]
We were accessing the iframe from the YT iframe api with `event.target.f` but apparently that's an internal property than changed in an update. Fixed by using `event.target.getIframe()` instead: e35409bceb8cec61169e410e999662ee434294f4
