### ISSUE TITLE
Bug reported with horizontal tabs on Twenty Twenty One with a js error related to bootstrap

### ISSUE THREAD

**Issue by covertnine** [covertnine/c9-blocks#39]
From WordPress.org:

Hi,
I’ve been having some problems with horizontal tabs, where clicking a tab link makes the page jump to the content and is a bit jarring. Seems like it’s not doing the preventdefault behaviour that is normally attached to these kinds of JS events. When looking at the console, I get an error that:

/wp-content/plugins/c9-blocks/src/vendor/bootstrap.min.js.map is missing.

Could this be the cause of the jumping? The file is not present in the plugin directory or anywhere that I can see…

Can you assist?
For extra info, this is on a multisite installation, using twentytwentyone theme, c9 blocks v.1.4.1

https://wordpress.org/support/topic/bootstrap-min-js-map-missing/#post-14617830

**Comment by htmercury** [comment]
resolved the /wp-content/plugins/c9-blocks/src/vendor/bootstrap.min.js.map sourcemap warning. Is the bug occurring on the editor side or front end? Can't seem to find the bug with the theme and plugin both activated. I'm interpreting this as bug where clicking on a "tab-1" button causes the page to scroll to tab-1-content into view.

**Comment by covertnine** [comment]
My guess would be the frontend. I wasn't able to replicate either.
