### ISSUE TITLE
Reverse column layout on mobile feature placeholder

### ISSUE THREAD

**Issue by covertnine** [covertnine/c9-blocks#40]
Placeholder thread for the flip column order on mobile.

The columns do flip as intended on mobile/tablet, but what I'd like to have happen is to be able to only flip the columns when they stack on mobile/tablet.

The point in stacking them in reverse on mobile is when you want the image or video that's normally to the right to be on the left on mobile cause that's what should be seen first before the text.

So if you can, try to make it so that the columns are only reversed when stacked.

So mobile, most things are 1 column--but for 6 column rows I believe they turn into 3x2 on mobile

4 column rows turn into 2x2 on mobile I believe.

It may make sense only to do this on 2 column and 3 column layouts in my opinion cause in 4-5-6 column layouts, it'd be strange to allow it to be reversed on mobile/tablet.

Would it be possible to have the column reverse sort only show up on 2 and 3 column layouts and then just leave the rest as-is?

I guess if we can get it working we can change the sort order on mobile for 4-5-6 columns, but I can't think of any instance where I've wanted to do that--only on 2 and 3 column ones.

See if you can get that on the next push. Looking forward to getting this in action on the sites!

-T

**Comment by htmercury** [comment]
https://github.com/covertnine/c9-blocks/commit/497313115415f41600d255cb70cb5cf060f4aaf5

Adjusted flip only takes effect on 2/3 column configurations and only reversed if columns are stacked

**Comment by covertnine** [comment]
Looks great after testing!
