### ISSUE TITLE
Add padding/margin classes to C9 columns, paragraphs, group blocks, C9 heading blocks, button blocks, blockquotes, pullquotes...

### ISSUE THREAD

**Issue by covertnine** [covertnine/c9-blocks#44]
Want to add the spacing classes to more blocks so we extend them and make it easier to micro-adjust specific settings related to margins and padding.

If there's a better interface element from WP with buttons to account for the margins/paddings instead of select dropdowns I'd be open to trying out some of those newer components as well if you think anything will work better!

-T

**Comment by htmercury** [comment]
I extended the padding and margin classes to currently (`core/paragraph, core/group, core/heading, core/buttons, core/button, core/spacer, core/quote, core/pullquote, c9-blocks/heading, c9-blocks/column`).. the extension uses the same UI as previously with select dropdowns. I am open to UI changes if we think of any
