### ISSUE TITLE
youtube API enable/disable option + front end feature of loading youtube videos manually without youtube API

### ISSUE THREAD

**Issue by htmercury** [covertnine/c9-blocks#65]
This feature has been added in develop as of commit 115a78ca2d39d34fbda7627149959c31a63c8fee

The toggle can be found under the C9 Blocks Side bar
![image](https://user-images.githubusercontent.com/20869604/168475437-c4f90925-a248-433b-bc84-a8e4a40e56cc.png)

The toggle is plugin wide so once enabled, all other pages/posts will have the youtube API disabled on the front end. (e.g. now youtube api script is conditionally enqueued based on the toggle value).

You can verify whether or not the youtube API is loaded on the front end via the network tab in inspector, specifically if this entry is missing or not.
![image](https://user-images.githubusercontent.com/20869604/168475519-76549069-a789-40b0-bdcb-7a1243e61a42.png)

**Comment by htmercury** [comment]
The toggle placement is open for feedback, it can be placed anywhere. initial thoughts was to have it in the side bar since its a plugin wide setting.

**Comment by htmercury** [comment]
feature is ready for testing.. youtube videos should still load fine without the api now on the front end

**Comment by covertnine** [comment]
Looks good, made a few minor CSS updates to fit it in there better. Pushing it up with the next release.
