### ISSUE TITLE
allow html to be rendered in posts grid block

### ISSUE THREAD

**Issue by htmercury** [covertnine/c9-blocks#66]
above feature is added along with commit a08cc90506c4e5dff2030de169f671bee5986c69 in develop

html in section title and titles in post entries can now be rendered e.g. i tag or b tag etc. To resolve security hazards, user input html is sanitized in php using wp_kses (https://developer.wordpress.org/reference/functions/wp_kses/) and on the editor side, react npm library interweave (https://www.npmjs.com/package/interweave) is added for sanitizing user html input on the editor react side.

be sure to npm i to include the new package. feature is ready for testing in develop.

**Comment by covertnine** [comment]
Merged this in with the next update.
