### ISSUE TITLE
Link dialogs persist on image carousel when linked

### ISSUE THREAD

**Issue by covertnine** [covertnine/c9-blocks#74]
This is a new thing I noticed with Wordpress 6.1. When you add a link to an image carousel block, the dialog that pops up persists even as the slides slide across, which overlaps with some of the controls.

To recreate:

- add image carousel
- add image
- link image
- switch to new slides
- you'll see the dialog never closes, it stays open with the link in it

See recordit below.
https://recordit.co/9kVMK3l1Zy

**Comment by htmercury** [comment]
Should be fixed now, reopen if not
