### ISSUE TITLE
Add to block editor globals 

### ISSUE THREAD

**Issue by covertnine** [covertnine/c9-blocks#76]
This CSS overrides some new backend CSS that causes width issues in the backend for our blocks that span full width of the editor. Can you put this in the block editor globals? I have something similar on the theme side.

`
/* backend widths for alignfull/alignwide and c9 grid inside of posts */
.is-sidebar-opened .editor-styles-wrapper .edit-post-visual-editor__post-title-wrapper>[data-type="c9-blocks/grid"]:where(:not(.alignleft):not(.alignright):not(.alignfull)),
.is-sidebar-opened .editor-styles-wrapper .block-editor-block-list__layout.is-root-container>[data-type="c9-blocks/grid"]:where(:not(.alignleft):not(.alignright):not(.alignfull)) {
    margin-left: calc((-100vw + 280px + 100%)/2) !important;
    margin-right: calc((-100vw + 280px + 100%)/2) !important;
}

/* backend widths for alignfull/alignwide and c9 grid inside of posts without sidebar opened */
.edit-post-layout .editor-styles-wrapper .edit-post-visual-editor__post-title-wrapper>[data-type="c9-blocks/grid"]:where(:not(.alignleft):not(.alignright):not(.alignfull)),
.edit-post-layout .editor-styles-wrapper .block-editor-block-list__layout.is-root-container>[data-type="c9-blocks/grid"]:where(:not(.alignleft):not(.alignright):not(.alignfull)) {
    margin-left: calc((-100vw + 100%)/2) !important;
    margin-right: calc((-100vw + 100%)/2) !important;
}
`

**Comment by covertnine** [comment]
Broken looks like screen shot below
<img width="1531" alt="Screenshot 2022-12-09 at 5 29 39 PM" src="https://user-images.githubusercontent.com/10245479/206811905-52cdac33-496a-4a26-aa7e-6283015f8516.png">

Fixed it should be centered with or without the sidebar like below.
<img width="1487" alt="Screenshot 2022-12-09 at 5 29 44 PM" src="https://user-images.githubusercontent.com/10245479/206811915-923495f5-0e0f-4a93-9f7b-1e909ee985a3.png">

**Comment by htmercury** [comment]
added the mentioned css to block editor globals, @covertnine check it out
