### ISSUE TITLE
Vertical Tabs Block Issue WIth Keyboard Entry closed after each character typed

### ISSUE THREAD

**Issue by covertnine** [covertnine/c9-blocks#77]
Found this one today. When changing the labels on the vertical tabs on the c9 starter theme and most recent version of WP 6.1.1, the keyboard entry 'saves' or closes after each character is entered so  I was not able to enter a label without clicking back into the block for every character.

Sort of a weird bug. See screen recording:

http://recordit.co/ZwIsn1R3Wd

**Comment by htmercury** [comment]
Should be fixed now, reopen if not
