### ISSUE TITLE
Horiz tab content doesn't change in editor with selected tab

### ISSUE THREAD

**Issue by hcoin** [covertnine/c9-blocks#87]
In version 1.6.7 and WP version 6.3.1:  Make a C9 horiz tab, create two tabs, put some content in each (like a list).  Notice there's no way to display the content other than the first tab.  Choosing different tabs highlights them, but does not refresh the content for editing.   Not even selecting the content directly on the menu to the left causes it to display.

Thanks for a great product!

**Comment by covertnine** [comment]
This should be fixed in the next release in a few days.

**Comment by covertnine** [comment]
This has been updated in the latest release v1.6.8
